version: "2.3"

services:
  php:
    build:
      context: .
      target: symfony_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      SYMFONY_VERSION:
    networks:
      - bdex-app
    links:
      - database
    depends_on:
      - database

  caddy:
    build:
      context: .
      target: symfony_caddy
    environment:
      SERVER_NAME: ${SERVER_NAME}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - bdex-app
    links:
      - php
      - database

  database:
    image: "mysql:5.7"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      bdex-app:
        ipv4_address: 172.119.1.3

networks:
  bdex-app:
    ipam:
      driver: default
      config:
        - subnet: 172.119.0.0/16
          ip_range: 172.119.1.0/24
          gateway: 172.119.0.254

volumes:
  caddy_data:
  caddy_config:
###> doctrine/doctrine-bundle ###
  mysql_data:
    driver: local
###< doctrine/doctrine-bundle ###
